---
title: "QC_pass_tables"
author: "Corey Cox"
date: "2/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(purrr)
library(UpSetR)
library(ComplexUpset)
library(table1)
library(scales)
```

## QC Passing samples



```{r qc_pass_samples}
# nasal_dna_pass_old <- read_excel("CAAPA2_Nasal_DNA_passing_manifest_20200201.xlsx") %>%
#    filter(! str_detect(`Sample ID`, "methyl")) %>% pluck("Sample ID")
# nasal_rna_pass_old <- read_excel("CAAPA2_Nasal_RNA_passing_manifest_20200201.xlsx") %>%
#   filter(! str_detect(`Sample ID`, "methyl")) %>% pluck("Sample ID")
# 
# pbmc_dna_pass_old <- read_excel("CAAPA2_PBMC_DNA_passing_manifest_20200201.xlsx") %>%
#   filter(! str_detect(`Sample ID`, "methyl")) %>% pluck("Sample ID")
# pbmc_rna_pass_old <- read_excel("CAAPA2_PBMC_RNA_passing_manifest_20200201.xlsx") %>%
#   filter(! str_detect(`Sample ID`, "methyl")) %>% pluck("Sample ID")

nasal_dna_pass <- read_excel("CAAPA2_Nasal_DNA_passing_manifest_20200208.xlsx") %>%
   filter(! str_detect(`Sample ID`, "methyl")) %>% pluck("Sample ID")
nasal_rna_pass <- read_excel("CAAPA2_Nasal_RNA_passing_manifest_20200208.xlsx") %>%
  filter(! str_detect(`Sample ID`, "methyl")) %>% pluck("Sample ID")

pbmc_dna_pass <- read_excel("CAAPA2_PBMC_DNA_passing_manifest_20200208.xlsx") %>%
  filter(! str_detect(`Sample ID`, "methyl")) %>% pluck("Sample ID")
pbmc_rna_pass <- read_excel("CAAPA2_PBMC_RNA_passing_manifest_20200208.xlsx") %>%
  filter(! str_detect(`Sample ID`, "methyl")) %>% pluck("Sample ID")

nasal_pass_all <- intersect(nasal_dna_pass, nasal_rna_pass)
pbmc_pass_all <- intersect(pbmc_dna_pass, pbmc_rna_pass)
pass_all <- intersect(nasal_pass_all, pbmc_pass_all)

# Get IDs that pass any 3 metrics
nasal_pass3 <- union(intersect(nasal_pass_all, pbmc_dna_pass),
                    intersect(nasal_pass_all, pbmc_rna_pass))
pbmc_pass3 <- union(intersect(pbmc_pass_all, nasal_dna_pass),
                    intersect(pbmc_pass_all, nasal_rna_pass))
pass3 <- union(nasal_pass3, pbmc_pass3)

nasal_rna_psomagen <- read_excel("CAAPA2_nasal_RNA_FINAL_manifest_for_Psomagen.xlsx") %>%
  filter(! str_detect(`Sample ID`, "methyl")) %>% pluck("Sample ID")

# intersect(nasal_rna_psomagen, pass_all) %>% nrow()
# intersect(nasal_rna_psomagen, nasal_dna_pass) %>% nrow()
# intersect(nasal_rna_psomagen, nasal_rna_pass) %>% nrow()
# 
# setdiff(nasal_rna_psomagen, nasal_dna_pass)
# 
# nasal_rna_pass_data <- read_excel("CAAPA_Nasal_RNA_passing_manifest_20200201.xlsx") %>%
#   filter(! str_detect(`Sample ID`, "methyl"))
# 
# nasal_rna_pass_data %>% filter(`Sample ID` %in% nasal_pass_all$`Sample ID`) %>%
#   filter(site == "Denver" & Asthma == "Case") %>% nrow
```

## QC input data

```{r input_data}
nasal_dna_input <- "../InputData2/Nasal_DNA_Final_for_plots_091720.csv" %>%
  # "../InputData/Nasal_DNA_Final_for_plots_072320_updated.csv" %>%
  read_csv(col_types = cols(subject = col_double(), site = col_character(), type = col_character(),
           Age_category = col_character(), Asthma = col_double(), Gender = col_double(),
           TOTAL_Nanodrop_ug = col_double(), TOTAL_Qubit_ug = col_double(),
           Nanodrop_260_280 = col_double(), Agilent_DIN = col_character(), Slide_status = col_character())) %>%
  mutate(Agilent_DIN = as.numeric(Agilent_DIN),
         Agilent_DIN = ifelse(is.na(Agilent_DIN), 0, Agilent_DIN))



nasal_rna_input <- "../InputData2/Nasal_RNA_Final_for_plots_091720.csv" %>%
  # "../InputData/Nasal_RNA_Final_for_plots_072320_updated.csv" %>%
  read_csv(col_types = cols(subject = col_double(), site = col_character(), type = col_character(),
           Age_category = col_character(), Asthma = col_double(), Gender = col_double(),
           TOTAL_Nanodrop_ug = col_double(), TOTAL_Qubit_ug = col_double(),
           Nanodrop_260_280 = col_double(), Agilent_RINe = col_double(), Slide_status = col_character()))

pbmc_dna_input <- "../InputData2/PBMC_DNA_Final_for_plots_091720.csv" %>%
  # "../InputData/PBMC_DNA_Final_for_plots_072320_updated.csv" %>%
  read_csv(col_types = cols(subject = col_double(), site = col_character(), type = col_character(),
           Age_category = col_character(), Asthma = col_double(), Gender = col_double(),
           TOTAL_Nanodrop_ug = col_double(), TOTAL_Qubit_ug = col_double(),
           Nanodrop_260_280 = col_double(), Agilent_DIN = col_double()))
pbmc_rna_input <- "../InputData2/PBMC_RNA_Final_for_plots_091720.csv" %>%
  # "../InputData/PBMC_RNA_Final_for_plots_072320_updated.csv" %>%
  read_csv(col_types = cols(subject = col_double(), site = col_character(), type = col_character(),
           Age_category = col_character(), Asthma = col_double(), Gender = col_double(),
           TOTAL_Nanodrop_ug = col_double(), TOTAL_Qubit_ug = col_double(),
           Nanodrop_260_280 = col_double(), Agilent_RINe = col_double()))

nasal_input <- full_join(nasal_dna_input, nasal_rna_input, suffix = c("_dna", "_rna"),
                         by = c("subject", "site", "Age_category", "Asthma", "Gender"))
pbmc_input <- full_join(pbmc_dna_input, pbmc_rna_input, suffix = c("_dna", "_rna"),
                         by = c("subject", "site", "Age_category", "Asthma", "Gender"))
all_input <- full_join(nasal_input, pbmc_input, suffix = c("_nasal", "_pbmc"),
                         by = c("subject", "site", "Age_category", "Asthma", "Gender"))



```

```{r tables}
# t1_input_pass <- 
# t1_labels <- list(variables = list("Total" = "Nasal DNA"), groups = list(""))
# t1_strata = c(Total = all_input_pass)
# table1(t1_strata, t1_labels, groupspan = c(1))
all_input_pass <- all_input %>%
  mutate("Nasal DNA" = ifelse(subject %in% nasal_dna_pass, "PASS", "FAIL"),
         "Nasal RNA" = ifelse(subject %in% nasal_rna_pass, "PASS", "FAIL"),
         "PBMC DNA" = ifelse(subject %in% pbmc_dna_pass, "PASS", "FAIL"),
         "PBMC RNA" = ifelse(subject %in% pbmc_rna_pass, "PASS", "FAIL"),
         "Nasal DNA & RNA" = ifelse(subject %in% nasal_pass_all, "PASS", "FAIL"),
         "PBMC DNA & RNA" = ifelse(subject %in% pbmc_pass_all, "PASS", "FAIL"),
         "Pass Any 3" = ifelse(subject %in% pass3, "PASS", "FAIL"),
         "Nasal & PBMC (DNA & RNA)" = ifelse(subject %in% pass_all, "PASS", "FAIL"))

table1(~ `Nasal DNA` + `Nasal RNA` + `Nasal DNA & RNA` +
         `PBMC DNA` + `PBMC RNA` + `PBMC DNA & RNA` +
         `Pass Any 3` + `Nasal & PBMC (DNA & RNA)` |
         site, data = all_input_pass)

upset_input <- list("Nasal DNA" = nasal_dna_pass, "Nasal RNA" = nasal_rna_pass,
                    "PBMC DNA" = pbmc_dna_pass, "PBMC RNA" = pbmc_rna_pass)
UpSetR::upset(fromList(upset_input), order.by = "freq",
      mainbar.y.label = "Subjects Passing Metric Set", sets.x.label = "Samples Passing Metric")
# Add colors for sites

all_pass_upset <- all_input %>%
  mutate("Nasal DNA" = ifelse(subject %in% nasal_dna_pass, "TRUE", "FALSE"),
         "Nasal RNA" = ifelse(subject %in% nasal_rna_pass, "TRUE", "FALSE"),
         "PBMC DNA" = ifelse(subject %in% pbmc_dna_pass, "TRUE", "FALSE"),
         "PBMC RNA" = ifelse(subject %in% pbmc_rna_pass, "TRUE", "FALSE"),
         "Nasal DNA & RNA" = ifelse(subject %in% nasal_pass_all, "TRUE", "FALSE"),
         "PBMC DNA & RNA" = ifelse(subject %in% pbmc_pass_all, "TRUE", "FALSE"),
         "Pass Any 3" = ifelse(subject %in% pass3, "TRUE", "FALSE"),
         "Nasal & PBMC (DNA & RNA)" = ifelse(subject %in% pass_all, "TRUE", "FALSE")) %>%
  mutate(across(c(site), as_factor))

upset(all_pass_upset, c("Nasal DNA", "Nasal RNA", "PBMC DNA", "PBMC RNA"),
      base_annotations = list('Subjects Passing Metric Sets' = intersection_size(counts = TRUE, mapping = aes(fill = site))),
      width_ratio=0.1)
```


```{r per_metric_upset}
DNA_metrics <- c("Agilent_DIN", "TOTAL_Qubit_ug", "TOTAL_Nanodrop_ug", "Nanodrop_260_280")
RNA_metrics <- c("TOTAL_Nanodrop_ug", "TOTAL_Qubit_ug", "Nanodrop_260_280", "Agilent_RINe")

QC_metrics_upset <- function(x, intx) {
  upset(x, intx, wrap = TRUE, width_ratio = 0.1, sort_sets = FALSE,
        base_annotations = list('Subjects Passing Metric Sets' = intersection_size(counts = TRUE, mapping = aes(fill = site))),
        set_sizes=( upset_set_size() + theme(axis.text.x=element_text(angle=45)) +
                      scale_y_continuous(breaks = breaks_pretty(n = 3), trans = "reverse")))
}

# QC_metrics_upset <- function(x, intx) {
#   upset(x, intx, wrap = TRUE, width_ratio = 0.1, sort_sets = FALSE,
#         base_annotations = list('Subjects Passing Metric Sets' = intersection_size(counts = TRUE, mapping = aes(fill = site))))
# }

Nasal_DNA_presummary <- read_tsv("Nasal_DNA_presummaryTable.tsv") %>%
  mutate(across(c("Slide_status", DNA_metrics), ~ .x == "PASS"))
# QC_metrics_upset(Nasal_DNA_presummary, DNA_metrics) + labs(title = "Nasal DNA Passing Metrics")
QC_metrics_upset(Nasal_DNA_presummary, c("Slide_status", DNA_metrics)) + labs(title = "Nasal DNA Passing Metrics")

Nasal_RNA_presummary <- read_tsv("Nasal_RNA_presummaryTable.tsv") %>%
  mutate(across(c("Slide_status", RNA_metrics), ~ .x == "PASS"))
# QC_metrics_upset(Nasal_RNA_presummary, RNA_metrics) + labs(title = "Nasal RNA Passing Metrics")
QC_metrics_upset(Nasal_RNA_presummary, c("Slide_status", RNA_metrics)) + labs(title = "Nasal RNA Passing Metrics")

PBMC_DNA_presummary <- read_tsv("PBMC_DNA_presummaryTable.tsv") %>%
  mutate(across(c("PBMC_cellcounts", DNA_metrics), ~ .x == "PASS"))
QC_metrics_upset(PBMC_DNA_presummary, c("PBMC_cellcounts", DNA_metrics)) + labs(title = "PBMC DNA Passing Metrics")

PBMC_RNA_presummary <- read_tsv("PBMC_RNA_presummaryTable.tsv") %>%
  mutate(across(c("PBMC_cellcounts", RNA_metrics), ~ .x == "PASS"))
QC_metrics_upset(PBMC_RNA_presummary, c("PBMC_cellcounts", RNA_metrics)) + labs(title = "PBMC RNA Passing Metrics")

all_sample_sites <- bind_rows(Nasal_RNA_presummary, Nasal_DNA_presummary, PBMC_DNA_presummary, PBMC_RNA_presummary) %>%
  select(subject, site, Asthma) %>% filter(! duplicated(subject))
```

```{r psomagen_upset}
psomagen_rna <- read_tsv("Psomagen_CAAPA2_RNA_QC.txt")

psomagen_rna_upset <- psomagen_rna %>% left_join(all_sample_sites, by = c("sample" = "subject")) %>%
  mutate(
    "<200ng" = `amount(ng)` < 200,
    "200-300ng" = `amount(ng)` >= 200 & `amount(ng)` < 300,
    "300-400ng" = `amount(ng)` >= 300 & `amount(ng)` < 400,
    "200-400ng" = `amount(ng)` >= 200 & `amount(ng)` < 400,
    "400-500ng" = `amount(ng)` >= 400 & `amount(ng)` < 500,
    ">500ng" = `amount(ng)` >= 500,
    "400-600ng" = `amount(ng)` >= 400 & `amount(ng)` < 600,
    ">600ng" = `amount(ng)` >= 600,
    "Asthma Case" = Asthma == "Case",
    "Asthma Control" = Asthma == "Control")

psomagen_rna_upset %>%
  upset(c("<200ng", "200-400ng", "400-600ng", ">600ng", "Asthma Case", "Asthma Control"),
        wrap = TRUE, width_ratio = 0.1, sort_sets = FALSE,
        base_annotations = list('Subjects Passing Metric Sets' = intersection_size(counts = TRUE, mapping = aes(fill = site))),
        set_sizes=( upset_set_size() + theme(axis.text.x=element_text(angle=45)) +
    scale_y_continuous(breaks = breaks_pretty(n = 3), trans = "reverse")))

psomagen_rna_upset %>%
  upset(c("<200ng", "200-300ng", "300-400ng", "400-500ng", ">500ng", "Asthma Case", "Asthma Control"),
        wrap = TRUE, width_ratio = 0.1, sort_sets = FALSE,
        base_annotations = list('Subjects Passing Metric Sets' = intersection_size(counts = TRUE, mapping = aes(fill = site))),
        set_sizes=( upset_set_size() + theme(axis.text.x=element_text(angle=45)) +
    scale_y_continuous(breaks = breaks_pretty(n = 3), trans = "reverse")))
```


```{r Nasal_DNA_upset}
nasal_dna_upset <- nasal_dna_input %>%
  mutate(
    "<250ng" = TOTAL_Qubit_ug < .25,
    "250ng-750ng" = TOTAL_Qubit_ug >= .25 & TOTAL_Qubit_ug < .75,
    "750ng-1ug" = TOTAL_Qubit_ug >= .75 & TOTAL_Qubit_ug < 1,
    "1-2ug" = TOTAL_Qubit_ug >= 1 & TOTAL_Qubit_ug < 2,
    "2-5ug" = TOTAL_Qubit_ug >= 2 & TOTAL_Qubit_ug < 5,
    ">5ug" = TOTAL_Qubit_ug >= 5,
    "Asthma Case" = Asthma == 2,
    "Asthma Control" = Asthma == 1,
    Asthma = as_factor(Asthma))

nasal_dna_upset %>%
  filter(site == "Baltimore" & subject > 10203057) %>%
  upset(c("<250ng", "250ng-750ng", "750ng-1ug", "1-2ug", "2-5ug", ">5ug"),
        wrap = TRUE, width_ratio = 0.1, sort_sets = FALSE,
        base_annotations = list('Subjects Passing Metric Sets' = intersection_size(counts = TRUE, mapping = aes(fill = Asthma))),
        set_sizes=( upset_set_size() + theme(axis.text.x=element_text(angle=45)) +
    scale_y_continuous(breaks = breaks_pretty(n = 3), trans = "reverse")))

nasal_dna_upset %>%
  upset(c("<200ng", "200-300ng", "300-400ng", "400-500ng", ">500ng", "Asthma Case", "Asthma Control"),
        wrap = TRUE, width_ratio = 0.1, sort_sets = FALSE,
        base_annotations = list('Subjects Passing Metric Sets' = intersection_size(counts = TRUE, mapping = aes(fill = site))),
        set_sizes=( upset_set_size() + theme(axis.text.x=element_text(angle=45)) +
    scale_y_continuous(breaks = breaks_pretty(n = 3), trans = "reverse")))
```
